# Generated by Django 4.0.1 on 2022-04-24 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0008_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='last_sent',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='timing',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
