# Generated by Django 4.0.1 on 2022-04-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_reports_last_sent_alter_reports_timing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='last_sent',
            field=models.DateTimeField(default='00:00', null=True),
        ),
    ]
